name: Doctochat Prod CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm install

      - name: Build
        run: CI=false npm run build
      - name: SSH Server Deploy MD
        uses: kostya-ten/ssh-server-deploy@v4
        with:
          host: '31.172.77.196'
          username: 'doctorchat-admin'
          password: ${{ secrets.APP_PASSWORD }}
          scp_source: "build/"
          scp_target: "/home/doctorchat-admin/htdocs/admin.doctorchat.md/"
      - name: Send notification to Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Deployed - Doctorchat Admin
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}

            Repository: ${{ github.repository }}

            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
            
